### ISSUE TITLE
feat: support JavaScript translations from edx-platform | FC-0012

### ISSUE THREAD

**Issue by OmarIthawi** [openedx/RecommenderXBlock#78]
@shadinaif please convert the lines below into the modern code base:

https://github.com/openedx/RecommenderXBlock/blob/c05fd6184b96e8113d2dc93a3924562cbffc82b0/recommender/recommender.py#L952-L964 (similar to https://github.com/openedx/xblock-drag-and-drop-v2/pull/365)

Also completely remove the `pkg_resource` translations in the deprecated PR: #77 (similar to https://github.com/openedx/xblock-drag-and-drop-v2/pull/352 )

**Comment by navinkarkera** [comment]
@OmarIthawi @shadinaif Is this already resolved by #77 ?

**Comment by navinkarkera** [comment]
@OmarIthawi Gentle reminder.

**Comment by OmarIthawi** [comment]
Yes @navinkarkera. Sorry for the delayed response.
